name: synthetic-offsets
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pyproj=3.0.1
  - numpy >= 1.18.1
  - matplotlib >= 3.1.1
  - netcdf4 >= 1.4.2
  - ipython >= 7.9.0
  - scipy >= 1.3.1
  - rasterio >= 1.1.0
  - geopandas >= 0.6.1
  - jupyterlab >= 3.0.9
  - rioxarray >= 0.5.0
  - pip
  - git
  - pip:
      - git+https://github.com/andy22b/synthetic_offsets/#subdirectory=src/synthetic_offsets